return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 3,
  nextobjectid = 3,
  properties = {},
  tilesets = {
    {
      name = "tilesetbase",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 1,
      image = "tileset01.png",
      imagewidth = 16,
      imageheight = 176,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 11,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 1,
      name = "Tilelaag 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      data = "CAAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAkAAAAEAAAAAwAAAAEAAAACAAAAAwAAAAIAAAACAAAAAwAAAAIAAAADAAAAAQAAAAEAAAADAAAAAwAAAAMAAAABAAAAAwAAAAIAAAABAAAAAgAAAAMAAAABAAAAAQAAAAMAAAABAAAAAwAAAAIAAAACAAAAAQAAAAIAAAADAAAABQAAAAQAAAABAAAAAgAAAAIAAAADAAAAAgAAAAMAAAADAAAAAgAAAAMAAAABAAAAAwAAAAEAAAABAAAAAQAAAAEAAAABAAAAAgAAAAMAAAADAAAAAgAAAAEAAAABAAAAAQAAAAMAAAABAAAAAgAAAAEAAAADAAAAAQAAAAIAAAAFAAAABAAAAAEAAAADAAAAAQAAAAEAAAACAAAAAQAAAAEAAAABAAAAAQAAAAEAAAADAAAAAQAAAAEAAAACAAAAAwAAAAEAAAABAAAAAwAAAAIAAAADAAAAAQAAAAEAAAABAAAAAQAAAAMAAAADAAAAAwAAAAMAAAABAAAAAQAAAAUAAAAEAAAAAwAAAAMAAAACAAAAAgAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAIAAAADAAAAAwAAAAMAAAACAAAAAQAAAAEAAAADAAAAAgAAAAMAAAACAAAAAwAAAAMAAAACAAAAAQAAAAMAAAADAAAABQAAAAQAAAADAAAAAgAAAAMAAAABAAAAAQAAAAEAAAACAAAAAQAAAAMAAAACAAAAAQAAAAMAAAABAAAAAwAAAAIAAAACAAAAAgAAAAEAAAADAAAAAgAAAAIAAAACAAAAAQAAAAMAAAABAAAAAQAAAAIAAAABAAAAAQAAAAMAAAAFAAAABAAAAAEAAAACAAAAAgAAAAIAAAADAAAAAgAAAAEAAAADAAAAAQAAAAMAAAABAAAAAgAAAAEAAAACAAAAAQAAAAMAAAADAAAAAgAAAAIAAAADAAAAAQAAAAIAAAACAAAAAQAAAAEAAAABAAAAAwAAAAIAAAADAAAAAQAAAAUAAAAEAAAAAgAAAAMAAAABAAAAAwAAAAIAAAADAAAAAQAAAAMAAAACAAAAAwAAAAMAAAACAAAAAgAAAAEAAAADAAAAAwAAAAIAAAADAAAAAQAAAAMAAAACAAAAAwAAAAIAAAABAAAAAgAAAAMAAAABAAAAAgAAAAMAAAADAAAABQAAAAQAAAABAAAAAwAAAAEAAAABAAAAAQAAAAEAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAACAAAAAwAAAAEAAAABAAAAAwAAAAIAAAACAAAAAgAAAAEAAAABAAAAAwAAAAMAAAACAAAAAgAAAAMAAAADAAAAAgAAAAMAAAAFAAAABAAAAAIAAAACAAAAAQAAAAMAAAABAAAAAQAAAAEAAAACAAAAAwAAAAIAAAADAAAAAwAAAAIAAAABAAAAAgAAAAEAAAACAAAAAgAAAAIAAAACAAAAAQAAAAMAAAABAAAAAQAAAAEAAAACAAAAAwAAAAEAAAACAAAAAQAAAAUAAAAEAAAAAgAAAAMAAAADAAAAAgAAAAMAAAABAAAAAQAAAAEAAAACAAAAAwAAAAIAAAABAAAAAwAAAAMAAAADAAAAAwAAAAIAAAABAAAAAgAAAAEAAAABAAAAAwAAAAMAAAABAAAAAgAAAAMAAAADAAAAAwAAAAMAAAACAAAABQAAAAQAAAADAAAAAgAAAAMAAAADAAAAAQAAAAIAAAABAAAAAQAAAAIAAAABAAAAAwAAAAMAAAADAAAAAwAAAAIAAAABAAAAAgAAAAIAAAACAAAAAQAAAAMAAAABAAAAAwAAAAMAAAABAAAAAwAAAAMAAAABAAAAAwAAAAEAAAAFAAAABAAAAAEAAAABAAAAAgAAAAIAAAADAAAAAgAAAAEAAAABAAAAAwAAAAEAAAABAAAAAQAAAAEAAAADAAAAAQAAAAEAAAADAAAAAQAAAAIAAAADAAAAAQAAAAMAAAABAAAAAgAAAAIAAAABAAAAAgAAAAMAAAADAAAAAgAAAAUAAAAEAAAAAQAAAAEAAAABAAAAAgAAAAEAAAACAAAAAgAAAAIAAAACAAAAAgAAAAEAAAADAAAAAgAAAAMAAAABAAAAAgAAAAEAAAABAAAAAgAAAAEAAAABAAAAAgAAAAMAAAACAAAAAwAAAAIAAAACAAAAAQAAAAIAAAADAAAABQAAAAQAAAADAAAAAwAAAAIAAAADAAAAAwAAAAMAAAABAAAAAQAAAAMAAAABAAAAAwAAAAIAAAACAAAAAwAAAAMAAAABAAAAAQAAAAEAAAABAAAAAwAAAAEAAAABAAAAAQAAAAIAAAADAAAAAQAAAAIAAAADAAAAAwAAAAEAAAAFAAAABAAAAAEAAAADAAAAAQAAAAMAAAABAAAAAQAAAAIAAAADAAAAAwAAAAMAAAADAAAAAgAAAAMAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAADAAAAAQAAAAEAAAADAAAAAwAAAAIAAAADAAAAAQAAAAEAAAACAAAAAgAAAAUAAAAEAAAAAQAAAAIAAAACAAAAAgAAAAEAAAABAAAAAQAAAAIAAAACAAAAAQAAAAMAAAADAAAAAgAAAAMAAAACAAAAAgAAAAEAAAABAAAAAQAAAAMAAAABAAAAAgAAAAEAAAACAAAAAQAAAAMAAAACAAAAAwAAAAEAAAACAAAABQAAAAQAAAABAAAAAgAAAAMAAAABAAAAAgAAAAIAAAADAAAAAgAAAAEAAAACAAAAAwAAAAMAAAADAAAAAwAAAAMAAAACAAAAAwAAAAIAAAADAAAAAQAAAAEAAAADAAAAAQAAAAEAAAADAAAAAwAAAAIAAAACAAAAAgAAAAMAAAAFAAAABAAAAAIAAAADAAAAAwAAAAMAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAwAAAAEAAAACAAAAAQAAAAEAAAADAAAAAgAAAAMAAAADAAAAAwAAAAMAAAACAAAAAgAAAAMAAAACAAAAAgAAAAEAAAABAAAAAwAAAAUAAAAEAAAAAgAAAAMAAAACAAAAAwAAAAIAAAACAAAAAwAAAAEAAAABAAAAAQAAAAEAAAADAAAAAQAAAAEAAAACAAAAAgAAAAEAAAACAAAAAgAAAAIAAAACAAAAAwAAAAMAAAACAAAAAwAAAAMAAAACAAAAAgAAAAEAAAABAAAABQAAAAQAAAACAAAAAQAAAAIAAAACAAAAAgAAAAEAAAACAAAAAwAAAAIAAAABAAAAAwAAAAIAAAABAAAAAQAAAAMAAAACAAAAAgAAAAEAAAACAAAAAgAAAAMAAAABAAAAAQAAAAEAAAACAAAAAgAAAAEAAAADAAAAAQAAAAEAAAAFAAAABAAAAAMAAAADAAAAAwAAAAEAAAABAAAAAwAAAAMAAAABAAAAAgAAAAIAAAACAAAAAgAAAAIAAAADAAAAAQAAAAEAAAABAAAAAQAAAAIAAAADAAAAAgAAAAIAAAADAAAAAgAAAAMAAAADAAAAAQAAAAIAAAADAAAAAwAAAAUAAAAEAAAAAgAAAAMAAAADAAAAAwAAAAIAAAABAAAAAgAAAAIAAAADAAAAAgAAAAEAAAACAAAAAQAAAAMAAAABAAAAAwAAAAMAAAADAAAAAQAAAAMAAAABAAAAAgAAAAIAAAACAAAAAgAAAAIAAAABAAAAAwAAAAIAAAADAAAABQAAAAQAAAADAAAAAQAAAAIAAAABAAAAAQAAAAEAAAADAAAAAgAAAAEAAAADAAAAAwAAAAMAAAABAAAAAgAAAAMAAAACAAAAAQAAAAMAAAABAAAAAwAAAAEAAAABAAAAAgAAAAEAAAABAAAAAQAAAAMAAAADAAAAAQAAAAIAAAAFAAAABAAAAAEAAAADAAAAAwAAAAEAAAADAAAAAwAAAAIAAAACAAAAAgAAAAIAAAADAAAAAgAAAAIAAAADAAAAAgAAAAIAAAACAAAAAwAAAAIAAAACAAAAAQAAAAEAAAADAAAAAgAAAAEAAAACAAAAAgAAAAMAAAACAAAAAQAAAAUAAAAEAAAAAgAAAAEAAAABAAAAAQAAAAEAAAABAAAAAwAAAAIAAAADAAAAAQAAAAIAAAABAAAAAgAAAAEAAAABAAAAAgAAAAMAAAACAAAAAgAAAAEAAAADAAAAAQAAAAEAAAACAAAAAwAAAAEAAAADAAAAAQAAAAIAAAACAAAABQAAAAQAAAACAAAAAQAAAAIAAAACAAAAAgAAAAMAAAADAAAAAgAAAAIAAAABAAAAAQAAAAMAAAABAAAAAgAAAAIAAAADAAAAAgAAAAMAAAACAAAAAQAAAAMAAAADAAAAAgAAAAIAAAADAAAAAwAAAAMAAAABAAAAAgAAAAMAAAAFAAAABAAAAAEAAAABAAAAAQAAAAMAAAADAAAAAwAAAAEAAAABAAAAAgAAAAMAAAACAAAAAgAAAAIAAAADAAAAAQAAAAMAAAACAAAAAgAAAAMAAAACAAAAAQAAAAEAAAADAAAAAwAAAAMAAAACAAAAAgAAAAEAAAADAAAAAwAAAAUAAAAEAAAAAwAAAAMAAAABAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAgAAAAIAAAABAAAAAQAAAAMAAAABAAAAAwAAAAEAAAACAAAAAQAAAAIAAAABAAAAAgAAAAEAAAACAAAAAwAAAAMAAAABAAAAAQAAAAIAAAABAAAABQAAAAQAAAABAAAAAwAAAAIAAAABAAAAAQAAAAIAAAACAAAAAwAAAAIAAAABAAAAAQAAAAMAAAADAAAAAQAAAAEAAAACAAAAAwAAAAEAAAADAAAAAwAAAAMAAAABAAAAAwAAAAIAAAACAAAAAwAAAAIAAAACAAAAAgAAAAEAAAAFAAAABAAAAAMAAAACAAAAAgAAAAEAAAABAAAAAwAAAAEAAAADAAAAAQAAAAIAAAADAAAAAgAAAAMAAAABAAAAAQAAAAEAAAADAAAAAgAAAAIAAAACAAAAAgAAAAMAAAADAAAAAwAAAAMAAAADAAAAAQAAAAEAAAABAAAAAwAAAAUAAAAKAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAACwAAAA=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Objectlaag 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "Player",
          class = "",
          shape = "rectangle",
          x = 256,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
